---
- hosts: "all" # применяем команды ко всем хостам из inventory
  become: true # становимся привилегированным пользователем
  roles:
    - nginx
    - postgres
    - ruby

  tasks:
    - name: "Reload nginx"
      ansible.builtin.service:
        name: "nginx"
        state: "reloaded"