---
- name: "ansible_practice"
  hosts: "all" # применяем команды ко всем хостам из inventory
  vars:
    SECRET_KEY_BASE: "any_string"
    RAILS_ENV: "production"
    RAILS_LOG_TO_STDOUT: "1"
    DB_HOST: "127.0.0.1"
    DB_PORT: "5432"
    DB_NAME: "xpaste"
    DB_USER: "xpaste"
    DB_PASSWORD: "Xpast271828"
    ruby_install_version: "2.5.1"

  become: true # становимся привилегированным пользователем
  roles:
    - nginx
    - postgres
    - ruby_install
    - ruby

  tasks:
  - name: "Set env variables"
    environment:
      SECRET_KEY_BASE: "any_string"
      RAILS_ENV: "production"
      RAILS_LOG_TO_STDOUT: "1"
      DB_HOST: "127.0.0.1"
      DB_PORT: "5432"
      DB_NAME: "xpaste"
      DB_USER: "xpaste"
      DB_PASSWORD: "Xpast271828"
      ruby_install_version: "2.5.1"
  - name: "Reload nginx"
    ansible.builtin.service:
      name: "nginx"
      state: "reloaded"